/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.chl.hajo.jsfs.bb;

import edu.chl.hajo.jsfs.mb.Shop;
import edu.chl.hajo.shop.core.Product;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

/**
 *
 * @author hajo
 */
@Named("addProduct")
@RequestScoped  // NOTE enterprise package, else disaster!!!
public class AddProductBB {

    private String name;
    private String price;
    private Shop shop = Shop.INSTANCE;

    public String save() {
        // Id generated by database
        Product p = new Product(name, Double.valueOf(price));
        shop.getProductCatalogue().add(p);
        return Navigation.PRODUCT_SUCCESS.toString();  // TODO
    }
    
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }
    
}
